#!/usr/bin/env python3
"""
agent/solvers/tora_solver.py — ToRA (Tool-integrated Reasoning Agent) solver.

ToRA pattern (Microsoft, ICLR 2024):
1. LLM receives a math word problem
2. LLM outputs step-by-step Python expressions as code
3. PythonExecutor runs expressions deterministically in a sandbox
4. Final answer extracted from the last computed variable

The LLM only needs to understand the problem structure and generate the
correct computation graph — all arithmetic is deterministic and error-free.

Usage:
    from agent.solvers.tora_solver import solve_with_tora
    answer = solve_with_tora(math_problem_text, llm, llm_infer_fn)
"""

from __future__ import annotations

import ast
import logging
import re
import sys
import textwrap
from typing import Any, Callable, Optional

logger = logging.getLogger("tora_solver")

# ---------------------------------------------------------------------------
# ToRA Prompt Template
# ---------------------------------------------------------------------------

TORA_SYSTEM_PROMPT = """\
You are a math problem solver. Solve the user's math problem step by step.

IMPORTANT RULES:
1. First, think about the problem in a natural way (do NOT write Python yet).
2. Then, write Python code to compute the answer.
3. Each step must assign a variable. Use clear variable names.
4. The LAST variable must be named `answer`.
5. Only use Python's standard library (no imports).
6. Use `print()` at the end to output the answer.
7. Put ALL your Python code inside a single ```python ... ``` block.
8. NEVER import sympy, numpy, or any external library. Use only basic arithmetic.

Example format:
User: Janet has 5 apples. She buys 3 more. Then she gives 2 to Tom. How many apples does she have?

Response:
Let's think step by step. Janet starts with 5, adds 3, then subtracts 2.

```python
start = 5
bought = 3
total_after_buy = start + bought
given = 2
answer = total_after_buy - given
print(answer)
```

Example 2 (discount/percentage):
User: Kylar wants to buy 16 glasses. One glass costs $5, but every second glass costs 60% of the price. How much does he need to pay?

```python
full_price = 16 // 2 * 5  # half are full price
discount_price = 16 // 2 * 5 * 0.6  # half are discount
answer = full_price + discount_price
print(answer)
```

Example 3 (multi-step with remaining):
User: Janet has $100. She spends $30 on groceries and then spends half of what's left on clothes. How much does she have left?

```python
after_groceries = 100 - 30
after_clothes = after_groceries / 2
answer = after_clothes
print(answer)
```
"""

TORA_USER_PROMPT = """\
Solve this math problem step by step, then write Python code to compute it.

Problem: {problem}

Put ALL your Python code inside a single ```python ... ``` block.
The last variable must be named `answer`. Print the answer."""


# ---------------------------------------------------------------------------
# Expression extraction from LLM output
# ---------------------------------------------------------------------------

_PYTHON_BLOCK_RE = re.compile(
    r"```python\s*\n(.*?)```",
    re.IGNORECASE | re.DOTALL,
)

_ANSWER_VAR_RE = re.compile(
    r"(?:answer|result|final|total)\s*=\s*(.+)",
    re.IGNORECASE,
)

_LAST_PRINT_RE = re.compile(
    r"print\((.+)\)\s*$",
    re.MULTILINE,
)


def extract_python_code(raw_output: str) -> Optional[str]:
    """Extract Python code from a ```python ... ``` block in the LLM output.

    Args:
        raw_output: The full text generated by the LLM.

    Returns:
        The Python code string, or None if no block found.
    """
    m = _PYTHON_BLOCK_RE.search(raw_output)
    if m:
        code = m.group(1).strip()
        if code:
            return code

    # Fallback: look for any code block
    m = re.search(r"```.*?\n(.*?)```", raw_output, re.DOTALL)
    if m:
        code = m.group(1).strip()
        if code and ("=" in code or "print" in code):
            return code

    # Last resort: try to extract raw Python lines (lines with = or print)
    lines = []
    for line in raw_output.split("\n"):
        stripped = line.strip()
        if re.match(r"^[a-zA-Z_]\w*\s*=", stripped) or stripped.startswith("print("):
            lines.append(stripped)
    if lines:
        return "\n".join(lines)

    return None


def extract_answer_from_execution(output: str) -> Optional[str]:
    """Extract the final answer from Python execution output.

    Args:
        output: The stdout from running the Python code.

    Returns:
        The answer string, or None if nothing found.
    """
    output = output.strip()
    if not output:
        return None
    # Take the last non-empty line
    lines = [l.strip() for l in output.split("\n") if l.strip()]
    if not lines:
        return None
    return lines[-1]


def extract_answer_from_code(code: str) -> Optional[str]:
    """Fallback: statically extract answer from code without executing.

    Looks for `answer = X` or `answer= X` patterns in the code.

    Args:
        code: The Python code string.

    Returns:
        The value string, or None.
    """
    # Find the last assignment to 'answer' or 'result'
    lines = code.strip().split("\n")
    answer_val = None
    for line in reversed(lines):
        stripped = line.strip()
        m = _ANSWER_VAR_RE.match(stripped)
        if m:
            answer_val = m.group(1).strip()
            break
    if answer_val is not None:
        return answer_val

    # Fallback: find the last expression printed
    for line in reversed(lines):
        stripped = line.strip()
        m = _LAST_PRINT_RE.match(stripped)
        if m:
            return m.group(1).strip()

    return None


# ---------------------------------------------------------------------------
# PythonExecutor — sandboxed subprocess execution
# ---------------------------------------------------------------------------

class ToraExecutionError(RuntimeError):
    """Raised when Python code execution fails or times out."""
    pass


def execute_python_safe(code: str, timeout: int = 10) -> str:
    """Execute Python code in a sandboxed subprocess.

    Uses the current Python interpreter but provides no access to the
    filesystem or network (just stdlib math operations).

    Args:
        code: Python code to execute.
        timeout: Max seconds to wait.

    Returns:
        Captured stdout as a string.

    Raises:
        ToraExecutionError: If the code times out, crashes, or has syntax errors.
    """
    import subprocess

    # Validate syntax before execution
    try:
        ast.parse(code)
    except SyntaxError as e:
        raise ToraExecutionError(f"Syntax error in generated code: {e}") from e

    try:
        proc = subprocess.run(
            [sys.executable, "-c", code],
            capture_output=True,
            text=True,
            timeout=timeout,
            env={"PYTHONIOENCODING": "utf-8"},
        )
    except subprocess.TimeoutExpired:
        raise ToraExecutionError(f"Python execution timed out after {timeout}s")

    if proc.returncode != 0:
        stderr = proc.stderr.strip()
        raise ToraExecutionError(
            f"Python execution failed (code={proc.returncode}): {stderr or '(no stderr)'}"
        )

    return proc.stdout.strip()


# ---------------------------------------------------------------------------
# High-level ToRA solver
# ---------------------------------------------------------------------------


def solve_with_tora(
    problem: str,
    llm: Any,
    infer_fn: Callable,
    max_tokens: int = 512,
    timeout: int = 10,
) -> Optional[str]:
    """Solve a math word problem using the ToRA pattern.

    Args:
        problem: The math word problem text.
        llm: The Llama model instance (only used for chat completion).
        infer_fn: A callable that takes (messages, max_tokens, stop_seqs, category)
                  and returns the LLM's response text.
                  Must match ``agent.pipeline.Pipeline._infer`` signature.
        max_tokens: Max tokens for the LLM response.
        timeout: Max seconds for Python execution.

    Returns:
        The answer string, or None if ToRA couldn't produce an answer.

    Example:
        >>> from agent.pipeline import Pipeline
        >>> pipe = Pipeline()
        >>> answer = solve_with_tora(
        ...     "Janet has 5 apples. She buys 3 more. How many?",
        ...     pipe._llm,
        ...     pipe._infer,
        ... )
        >>> print(answer)
        "8"
    """
    # Build messages
    messages = [
        {"role": "system", "content": TORA_SYSTEM_PROMPT},
        {"role": "user", "content": TORA_USER_PROMPT.format(problem=problem)},
    ]

    # 1. Generate Python code from LLM
    try:
        # infer_fn must accept (messages, max_tok, stop_seq, ...) per Pipeline._infer
        raw_output = infer_fn(
            messages,
            max_tok=max_tokens,  # noqa — Pipeline uses 'max_tok' not 'max_tokens'
            stop_seq=[],
            timeout=28.0,
            category="math",
        )
    except Exception as e:
        logger.warning("ToRA LLM inference failed: %s", e)
        return None

    if not raw_output or not raw_output.strip():
        logger.debug("ToRA: empty LLM output")
        return None

    logger.debug("ToRA raw output (first 200): %s...", raw_output[:200])

    # 2. Extract Python code from LLM output
    code = extract_python_code(raw_output)
    if not code:
        logger.debug("ToRA: no Python code block found in LLM output")
        # Try static extraction as last resort
        static_answer = extract_answer_from_code(raw_output.replace("\n\n", "\n"))
        if static_answer:
            logger.debug("ToRA: static extraction gave answer=%s", static_answer)
            return static_answer
        return None

    logger.debug("ToRA extracted code:\n%s", code)

    # 3. Execute code
    try:
        stdout = execute_python_safe(code, timeout=timeout)
    except ToraExecutionError as e:
        logger.warning("ToRA execution error: %s", e)
        return None

    # 4. Extract answer from execution output
    answer = extract_answer_from_execution(stdout)
    if answer is not None:
        logger.debug("ToRA: answer=%s from code execution", answer)
        return answer

    # 5. Fallback: extract from code statically
    static_answer = extract_answer_from_code(code)
    if static_answer is not None:
        logger.debug("ToRA: static fallback answer=%s", static_answer)
        return static_answer

    return None


# ---------------------------------------------------------------------------
# Batch solver for GSM8K evaluation
# ---------------------------------------------------------------------------


def solve_with_tora_batch(
    problems: list[dict[str, str]],
    llm: Any,
    infer_fn: Callable,
    max_tokens_per_problem: int = 512,
    timeout_per_execution: int = 10,
) -> list[dict[str, Any]]:
    """Run ToRA solver over a batch of problems.

    Args:
        problems: Each dict has 'prompt' (or 'question') and optionally 'expected_answer'.
        llm: Llama model instance.
        infer_fn: Callable for LLM inference (matches Pipeline._infer signature).
        max_tokens_per_problem: Max tokens per LLM call.
        timeout_per_execution: Max seconds per Python execution.

    Returns:
        List of result dicts: {'prompt': ..., 'answer': ..., 'expected': ..., 'correct': bool}
    """
    results: list[dict[str, Any]] = []
    for item in problems:
        prompt = item.get("prompt", item.get("question", ""))
        expected = item.get("expected_answer", "")

        try:
            answer = solve_with_tora(
                prompt, llm, infer_fn,
                max_tokens=max_tokens_per_problem,
                timeout=timeout_per_execution,
            )
        except Exception as e:
            logger.error("ToRA batch error on %r: %s", prompt[:60], e)
            answer = None

        results.append({
            "prompt": prompt,
            "answer": answer or "",
            "expected": expected,
            "correct": None,  # caller should set with fuzzy_match
        })

    return results


__all__ = [
    "solve_with_tora",
    "solve_with_tora_batch",
    "extract_python_code",
    "extract_answer_from_execution",
    "TORA_SYSTEM_PROMPT",
    "TORA_USER_PROMPT",
]
