"""
agent/qc_config.py — Fine-tuned Quality Control Configuration.

Generated by fine_tune_qc.py with V4 improved classifier (85.4% on eval_all_300).
Per-category thresholds tuned on stage2 validation set (26876 items).
"""

QC_CONFIG = {
    "code_debug": {
        "metric": "top3_gap",
        "threshold": 2.6667,
        # (insufficient data, using global fallback)
    },
    "code_gen": {
        "metric": "margin",
        "threshold": 0.6,
        # prec=1.000
    },
    "factual": {
        "metric": "inverse_active",
        "threshold": 1.0,
        # prec=1.000
    },
    "logic": {
        "metric": "top3_gap",
        "threshold": 2.6667,
        # (insufficient data, using global fallback)
    },
    "math": {
        "metric": "max_score",
        "threshold": 2.0,
        # prec=0.911
    },
    "ner": {
        "metric": "top_over_avg",
        "threshold": 4.444444444444445,
        # prec=0.922
    },
    "sentiment": {
        "metric": "top3_gap",
        "threshold": 2.6667,
        # (insufficient data, using global fallback)
    },
    "summarization": {
        "metric": "top3_gap",
        "threshold": 2.6667,
        # (insufficient data, using global fallback)
    },
}

GLOBAL_QC = {
    "metric": "top3_gap",
    "threshold": 2.666666666666667,
}

QC_POLICY = {
    "on_fail": "escalate",
    "min_accept_precision": 0.85,
    "fallback_solvers": True,
}
